# Generated by Django 5.0.3 on 2024-03-13 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_post_delete_posy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time_create",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 13, 15, 19, 21, 186826)
            ),
        ),
    ]
