# Generated by Django 5.0.3 on 2024-03-13 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_post_time_create"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time_create",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 13, 16, 50, 3, 917157)
            ),
        ),
    ]
